INSERT INTO 
	TBL_BOOKS (BOOK_TITLE, ISBN, AUTHOR, GENRE, QUANTITY) 
VALUES
  	('Spring Boot', 'HSCSIUN8978798', 'Ryan Kelly', 'LEARNING', 10),
  	('Microservices Patterns', 'JGUGH787878', 'JOHN HAMMOND', 'LEARNING', 10);