DROP TABLE IF EXISTS TBL_BOOKS;
 
CREATE TABLE TBL_BOOKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  BOOK_TITLE VARCHAR(250) NOT NULL,
  ISBN VARCHAR(250) NOT NULL,
  AUTHOR VARCHAR(250) DEFAULT NULL,
  GENRE VARCHAR(250) DEFAULT NULL,
  QUANTITY INTEGER DEFAULT NULL
);